### ISSUE TITLE
Cannot deploy aws launch wizard for sap using SLES BYOS

### ISSUE THREAD

**Issue by sapien47** [awsdocs/aws-launch-wizard-user-guide#2]
Hello,

I cannot deploy AWS Launch Wizard for SAP using SLES for SAP BYOS.
The scripted SLES for SAP  Registration fails, the repositories are therefore not added, the whole deployment is just waiting until it fails.

```
_2022-02-06 18:10:44,178 INFO:Writing SMT rootCA: /usr/share/pki/trust/anchors
2022-02-06 18:10:44,195 INFO:Updating CA certificates: update-ca-certificates
2022-02-06 18:10:45,856 ERROR:Registration with ('52.60.50.162', None) failed. Trying ('52.60.53.175', None)
2022-02-06 18:10:45,857 INFO:Clean current registration server: ('52.60.50.162', None)
2022-02-06 18:10:45,888 INFO:System sucessfully removed from update infrastructure
2022-02-06 18:10:45,890 INFO:Removing credentials: /etc/zypp/credentials.d/SCCcredentials
2022-02-06 18:10:45,890 INFO:Modified /etc/hosts, added: 52.60.53.175   [smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=G6GJBKA8gfP0EzrDMIQNK97XD5aXu91n7nmRD9kB4VM%3D&reserved=0)   smt-ec2

2022-02-06 18:10:47,268 ERROR:Registration with ('52.60.53.175', None) failed. Trying ('52.60.53.224', None)
2022-02-06 18:10:47,268 INFO:No current registration server set.
2022-02-06 18:10:47,268 INFO:Modified /etc/hosts, added: 52.60.53.224   [smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=G6GJBKA8gfP0EzrDMIQNK97XD5aXu91n7nmRD9kB4VM%3D&reserved=0)   smt-ec2

2022-02-06 18:10:48,645 ERROR:Baseproduct registration failed
2022-02-06 18:10:48,645 ERROR:  Registering system to registration proxy [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0)

Updating system details on [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0) ...

Activating SLES_SAP 15.2 x86_64 ...
Error: Registration server returned 'Instance verification failed: Product/instance type mismatch' (422)_
```

I then double checked, triple checked our SLES for SAP Subscription : 
* I started several EC2  instances on the AWS consoles using SLES for SAP 15 SP2, and SP1 and SP0 images, and then manually registered the subscription, it worked every time with the very same registration code that failed in the Wizard.
* I even created a new new subscription in the SUSE Console, the subscription code works when I registered it manually, but it failed when I provided the same SUSE BYOS Registration code in the Wizard

Interestingly, after the automatic and scripted registration failed, I connected to the same EC2 instance and I tried to manually register the subscription,  and it worked, but I had to do a SuseConnect cleanup first, unfortunately, that won't solve my issue, but proves that the problem is not with our subscription:

```
_**sapci:/home/ec2-user # SUSEConnect -r IXXXXXXXXXXXXXX8**
Registering system to registration proxy [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0)

Updating system details on [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0) ...

Activating SLES_SAP 15.2 x86_64 ...
**Error: Registration server returned 'Instance verification failed: Product/instance type mismatch' (422)**
**sapci:/home/ec2-user # SUSEConnect --cleanup
sapci:/home/ec2-user # SUSEConnect -r IXXXXXXXXXXXXXX8**
Registering system to registration proxy [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0)

Announcing system to [https://smt-ec2.susecloud.net](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmt-ec2.susecloud.net%2F&data=04%7C01%7Cfarid.brahimi%40createch.ca%7Cb6926b32ad1f43355dac08d9e9a03549%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637797696567778150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=y7QeyfkevTp8a93vGsuUq8eR5wI6nJdS0BJrYRQ9Abk%3D&reserved=0) ...

Activating SLES_SAP 15.2 x86_64 ...
-> Adding service to system ...

Activating sle-module-basesystem 15.2 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

Activating sle-module-server-applications 15.2 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

Activating sle-ha 15.2 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

Activating sle-module-sap-applications 15.2 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

Activating sle-module-desktop-applications 15.2 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

**Successfully registered system**

sapci:/home/ec2-user #_
```

**Comment by picoroma** [comment]
I have similar issue deploying SAP BW4 2021 with LW.
Seems that the EC2 is not registered on SUSEConnect and the Wizard do not finish.
OPENed a AWS CASE for this. But still no solution

**Comment by sapien47** [comment]
> I have similar issue deploying SAP BW4 2021 with LW. Seems that the EC2 is not registered on SUSEConnect and the Wizard do not finish. OPENed a AWS CASE for this. But still no solution

Thank you for the confirmation

**Comment by sapien47** [comment]
Anyone from AWS reading this or acknowledging the bug ?
We have a large SAP on SLES deployment on hold. Without the option to use BYOS for Suse, the Launch Wizard is basically unusable.

thanks

**Comment by jmjesse** [comment]
Thanks for reaching out to AWS Documentation. I want to first apologize for the delay in our response time! I appreciate your patience and thank you for bringing this to our attention. I did some research on my side and found that the team is working to address this issue. They had the following to share:

> AWS Launch Wizard service will rollout the fix to handle SUSE updates in registration of BYOS AMI’s to all regions by 3/4.

**Comment by sapien47** [comment]
> rollout the fix to

Great, very appreciated !

**Comment by picoroma** [comment]
Hi Jessie,by 3/4 means 3 or 4 days or the 3rd of April?ThxP.Il 22 feb 2022 20:56, Jesse J ***@***.***> ha scritto:

Thanks for reaching out to AWS Documentation. I want to first apologize for the delay in our response time! I appreciate your patience and thank you for bringing this to our attention. I did some research on my side and found that the team is working to address this issue. They had the following to share:



AWS Launch Wizard service will rollout the fix to handle SUSE updates in registration of BYOS AMI’s to all regions by 3/4.

**Comment by jmjesse** [comment]
Sorry for any confusion on the timing here. The rollout ETA (for all regions) is actually for March 4th.

**Comment by jmjesse** [comment]
I wanted to circle back on this issue and confirm if it has been resolved. Can you please provide an update on whether this can be closed?

**Comment by picoroma** [comment]
Unfortunately I still have problems.
Always related to SUSE registration.
But not only....
Yesterday I test twice with almost the same settings:
- Ones the EC2 was registered on SUSEConnect - But after the DEPLOYanyway remain in Standby
- Ones the EC2 was NOT registered
I have also test with a AWS Marketplace AMI (and the rest of setting identical). And in this case the DEPLOY goes on and finish correctly.

**Comment by picoroma** [comment]
I'm performing another DEPLOY that is having the same problems.
I collected the "install.log" (under /root/install/script/log folder) and updated the AWS CASE I have opened (Case ID 9633219161)
As I can see in the log - the problem starts just after the end of PHASE "PRE_INSTALL_COMPLETE".
I think at this point the new EBS volume should be attached to EC2 instance, but this do not happens and the DEPLOY hangs indefinitively.

**Comment by jmjesse** [comment]
I'm sorry to hear you're still having some issues with the deployments through Launch Wizard. I would recommend continuing to troubleshoot the issue with the support engineering team for the best assistance on this technical issue and to avoid duplicating troubleshooting efforts.

**Comment by jmjesse** [comment]
Can I get confirmation if this issue was resolved? It's been inactive for some time. Thanks!

**Comment by picoroma** [comment]
No. Case is still open and it is in charge of aws support at the moment.

**Comment by jmjesse** [comment]
I have received confirmation that support case 9633219161 has been resolved. I'll go ahead and close up this PR.
